# Generated by Django 3.0.8 on 2022-07-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home',
            new_name='Product',
        ),
    ]
